In [129]:
#Create a query or queries to extract the information you think may be relevant for building the prediction model. 
#It should include some film features and some rental features (X).


In [130]:
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import getpass  # To get the password without showing the input
password = getpass.getpass()

········


In [131]:
# get the data
connection_string = 'mysql+pymysql://root:' + password + '@localhost/sakila'
engine = create_engine(connection_string)
query = '''SELECT
    f.film_id,
    f.title,
    f.release_year,
    f.language_id,
    f.rental_duration,
    f.rental_rate,
    f.length,
    f.rating,
    COUNT(CASE WHEN MONTH(r.rental_date) = 5 AND YEAR(r.rental_date) = 2005 THEN r.rental_id ELSE NULL END) AS rentals_count
FROM
    film AS f
LEFT JOIN
    inventory AS i ON f.film_id = i.film_id
LEFT JOIN
    rental AS r ON i.inventory_id = r.inventory_id
GROUP BY
    f.film_id
ORDER BY
    rentals_count DESC;'''



data = pd.read_sql_query(query, engine)
data.head(10)

film_id               title  release_year  language_id  rental_duration  \
0      103  BUCKET BROTHERHOOD          2006            1                7   
1      450     IDOLS SNATCHERS          2006            1                5   
2      735        ROBBERS JOON          2006            1                7   
3       86       BOOGIE AMELIE          2006            1                6   
4      159         CLOSER BANG          2006            1                5   
5      284          ENEMY ODDS          2006            1                5   
6      285    ENGLISH BULWORTH          2006            1                3   
7      303    FANTASY TROOPERS          2006            1                6   
8      305       FATAL HAUNTED          2006            1                6   
9      309        FEUD FROGMEN          2006            1                6   

   rental_rate  length rating  rentals_count  
0         4.99     133     PG              5  
1         2.99      84  NC-17              5  
2         2.99     102  PG-13              5  
3         4.99     121      R              4  
4         4.99      58      R              4  
5         4.99      77  NC-17              4  
6         0.99      51  PG-13              4  
7         0.99      58  PG-13              4  
8         2.99      91     PG              4  
9         0.99      98      R              4

In [132]:
data = pd.read_sql_query(query, engine)
data.head(50)

film_id                   title  release_year  language_id  \
0       103      BUCKET BROTHERHOOD          2006            1   
1       450         IDOLS SNATCHERS          2006            1   
2       735            ROBBERS JOON          2006            1   
3        86           BOOGIE AMELIE          2006            1   
4       159             CLOSER BANG          2006            1   
5       284              ENEMY ODDS          2006            1   
6       285        ENGLISH BULWORTH          2006            1   
7       303        FANTASY TROOPERS          2006            1   
8       305           FATAL HAUNTED          2006            1   
9       309            FEUD FROGMEN          2006            1   
10      331          FORWARD TEMPLE          2006            1   
11      374           GRAFFITI LOVE          2006            1   
12      382          GRIT CLOCKWORK          2006            1   
13      395       HANDICAP BOONDOCK          2006            1   
14      417         HILLS NEIGHBORS          2006            1   
15      535           LOVE SUICIDES          2006            1   
16      563          MASSACRE USUAL          2006            1   
17      621            NETWORK PEAK          2006            1   
18      646         OUTBREAK DIVINE          2006            1   
19      650         PACIFIC AMISTAD          2006            1   
20      702            PULP BEVERLY          2006            1   
21      730     RIDGEMONT SUBMARINE          2006            1   
22      738        ROCKETEER MOTHER          2006            1   
23      745          ROSES TREASURE          2006            1   
24      775     SEATTLE EXPECATIONS          2006            1   
25      875       TALENTED HOMICIDE          2006            1   
26      891          TIMBERLAND SKY          2006            1   
27      941       VIDEOTAPE ARSENIC          2006            1   
28      958        WARDROBE PHANTOM          2006            1   
29      979           WITCHES PANIC          2006            1   
30        8         AIRPORT POLLOCK          2006            1   
31       26          ANNIE IDENTITY          2006            1   
32       28             ANTHEM LUKE          2006            1   
33       31           APACHE DIVINE          2006            1   
34       48     BACKLASH UNDEFEATED          2006            1   
35       55    BARBARELLA STREETCAR          2006            1   
36       59          BEAR GRACELAND          2006            1   
37       73          BINGO TALENTED          2006            1   
38       78        BLACKOUT PRIVATE          2006            1   
39      101     BROTHERHOOD BLANKET          2006            1   
40      109      BUTTERFLY CHOCOLAT          2006            1   
41      117          CANDLES GRAPES          2006            1   
42      130          CELEBRITY HORN          2006            1   
43      131         CENTER DINOSAUR          2006            1   
44      135     CHANCE RESURRECTION          2006            1   
45      140           CHEAPER CLYDE          2006            1   
46      142    CHICKEN HELLFIGHTERS          2006            1   
47      164           COAST RAINBOW          2006            1   
48      167               COMA HEAD          2006            1   
49      174  CONFIDENTIAL INTERVIEW          2006            1   

    rental_duration  rental_rate  length rating  rentals_count  
0                 7         4.99     133     PG              5  
1                 5         2.99      84  NC-17              5  
2                 7         2.99     102  PG-13              5  
3                 6         4.99     121      R              4  
4                 5         4.99      58      R              4  
5                 5         4.99      77  NC-17              4  
6                 3         0.99      51  PG-13              4  
7                 6         0.99      58  PG-13              4  
8                 6         2.99      91     PG     

In [133]:
data.isna().sum()

film_id            0
title              0
release_year       0
language_id        0
rental_duration    0
rental_rate        0
length             0
rating             0
rentals_count      0
dtype: int64

In [134]:
data.shape

(1000, 9)

In [135]:
#Create a query to get the list of all unique film titles and a boolean indicating if it was rented (rental_date) in May 2005.
#(Create new column called - 'rented_in_may'). This will be our TARGET (y) variable.


In [136]:
sql_query = """
SELECT DISTINCT
    f.title,
    CASE
        WHEN COUNT(r.rental_id) > 0 THEN 1
        ELSE 0
    END AS rented_in_may
FROM
    film f
LEFT JOIN
    inventory i ON f.film_id = i.film_id
LEFT JOIN
    rental r ON i.inventory_id = r.inventory_id AND MONTH(r.rental_date) = 5 AND YEAR(r.rental_date) = 2005
GROUP BY
    f.title
"""

data2 = pd.read_sql(sql_query, engine)
data2

title  rented_in_may
0     ACADEMY DINOSAUR              1
1       ACE GOLDFINGER              0
2     ADAPTATION HOLES              1
3     AFFAIR PREJUDICE              1
4          AFRICAN EGG              1
..                 ...            ...
995     YOUNG LANGUAGE              0
996         YOUTH KICK              0
997       ZHIVAGO CORE              1
998  ZOOLANDER FICTION              1
999          ZORRO ARK              1

[1000 rows x 2 columns]

In [137]:
df = pd.merge(data, data2, on='title')
df.drop(["title","film_id"],axis=1, inplace=True)
df.head()
df.shape

(1000, 8)

In [138]:
df.head()

release_year  language_id  rental_duration  rental_rate  length rating  \
0          2006            1                7         4.99     133     PG   
1          2006            1                5         2.99      84  NC-17   
2          2006            1                7         2.99     102  PG-13   
3          2006            1                6         4.99     121      R   
4          2006            1                5         4.99      58      R   

   rentals_count  rented_in_may  
0              5              1  
1              5              1  
2              5              1  
3              4              1  
4              4              1

In [139]:
# Analyze extracted features (X) and transform them. You may need to 
# encode some categorical variables, or scale numerical variables.


In [140]:
import matplotlib.pyplot as plt
import seaborn as sns

In [141]:
y = df['rented_in_may']
X = df.drop('rented_in_may', axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1337)

In [143]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

X_train_num = X_train.select_dtypes(include = np.number)
X_test_num=X_test.select_dtypes(include=np.number)
# Scaling data
transformer = MinMaxScaler().fit(X_train_num) # need to keep transformer
X_train_normalized = transformer.transform(X_train_num)
X_train_norm = pd.DataFrame(X_train_normalized, columns=X_train_num.columns)
X_train_norm


release_year  language_id  rental_duration  rental_rate    length  \
0             0.0          0.0             0.00          0.0  0.546763   
1             0.0          0.0             0.50          0.0  0.625899   
2             0.0          0.0             0.25          0.5  0.122302   
3             0.0          0.0             0.75          0.5  0.474820   
4             0.0          0.0             0.00          0.0  0.194245   
..            ...          ...              ...          ...       ...   
795           0.0          0.0             1.00          1.0  0.762590   
796           0.0          0.0             0.25          0.5  0.726619   
797           0.0          0.0             0.00          0.5  0.179856   
798           0.0          0.0             0.50          0.5  0.402878   
799           0.0          0.0             0.50          1.0  0.827338   

     rentals_count  
0              0.6  
1              0.0  
2              0.0  
3              0.4  
4              0.6  
..             ...  
795            0.4  
796            0.4  
797            0.0  
798            0.4  
799            0.4  

[800 rows x 6 columns]

In [145]:
X_test_normalized = transformer.transform(X_test_num)
X_test_norm = pd.DataFrame(X_test_normalized, columns=X_test_num.columns)
X_test_norm


release_year  language_id  rental_duration  rental_rate    length  \
0             0.0          0.0             0.25          0.5  0.316547   
1             0.0          0.0             0.75          0.0  0.971223   
2             0.0          0.0             0.75          0.0  0.438849   
3             0.0          0.0             0.25          1.0  0.776978   
4             0.0          0.0             0.00          0.5  0.719424   
..            ...          ...              ...          ...       ...   
195           0.0          0.0             1.00          0.0  0.856115   
196           0.0          0.0             0.00          1.0  0.330935   
197           0.0          0.0             0.75          1.0  0.971223   
198           0.0          0.0             1.00          1.0  0.748201   
199           0.0          0.0             0.50          0.0  0.330935   

     rentals_count  
0              0.0  
1              0.8  
2              0.6  
3              0.0  
4              0.0  
..             ...  
195            0.0  
196            0.2  
197            0.2  
198            0.0  
199            0.2  

[200 rows x 6 columns]

In [146]:
X_train_categorical = X_train.select_dtypes(include = object)
X_train_cat = pd.get_dummies(X_train_categorical, 
                             columns=['rating'],
                             drop_first=True,dtype=float)
X_train_cat.head()

rating_NC-17  rating_PG  rating_PG-13  rating_R
46            0.0        1.0           0.0       0.0
789           0.0        0.0           1.0       0.0
722           0.0        0.0           0.0       0.0
283           1.0        0.0           0.0       0.0
39            0.0        0.0           0.0       1.0

In [147]:
X_test_categorical = X_test.select_dtypes(include = object)
X_test_cat = pd.get_dummies(X_test_categorical, 
                             columns=['rating'],
                             drop_first=True,dtype=float)
X_test_cat.head()

rating_NC-17  rating_PG  rating_PG-13  rating_R
977           0.0        0.0           0.0       1.0
15            0.0        0.0           0.0       1.0
56            0.0        1.0           0.0       0.0
801           0.0        0.0           0.0       1.0
747           0.0        1.0           0.0       0.0

In [148]:
X_train_transformed = np.concatenate([X_train_norm, X_train_cat], axis=1)

In [149]:
X_train_transformed

array([[0.  , 0.  , 0.  , ..., 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , ..., 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.25, ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.5 , ..., 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.5 , ..., 0.  , 0.  , 0.  ]])

In [150]:
X_test_transformed = np.concatenate([X_test_norm, X_test_cat], axis=1)

In [151]:
X_test_transformed

array([[0.  , 0.  , 0.25, ..., 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.75, ..., 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.75, ..., 1.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.75, ..., 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.5 , ..., 0.  , 0.  , 0.  ]])

In [152]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs',
                  multi_class='multinomial').fit(X_train_transformed, y_train)

In [154]:
predictions = classification.predict(X_test_transformed)
classification.score(X_test_transformed, y_test)


1.0

In [155]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[ 61,   0],
       [  0, 139]], dtype=int64)